apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-ngnix
  namespace: argocd
spec:
  project: default
  source:
    repoURL:  'git@github.com:michaeldallen/Mastering-GitOps-with-Argo-CD.git'
    path: section04lesson13/nginx
    targetRevision: master
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      
