apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpd
  namespace: argocd
spec:
  project: default
  source:
    chart: httpd
    repoURL:  https://mw-docker.repositories.mathworks.com/mallen/httpd
    targetRevision: 0.1.0
    helm:
      releaseName: httpd-rel
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      
    
