apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpd
  namespace: argocd
spec:
  project: default
  sources:
    - chart: httpd
      repoURL:  mw-docker.repositories.mathworks.com/mallen
      targetRevision: 1.4.5
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      
    
